### ISSUE TITLE
Venue for DevOpsDays 2016

### ISSUE THREAD

**Issue by jfryman** [DevOpsDaysBNA/discussions#1]
We need a venue to have our very first DevOpsDays BNA. To than end, let's set out some parameters and start scoping out places. This is our first showing in Nashville, so I am unclear as to what to expect. For our first, we try to account for 150-200 attendees.

To that end, what places could we scope out? What companies or places are available that we might be able to get sponsorship to use (either directly with space usage, or indirectly with funds... see #2  issue).

Tentative dates: Nov 10-11

**Comment by cwage** [comment]
Is 150-200 people based on other cities' turnout or just a guesstimate?

Do we have any idea what the target presentation size & number will be? .. guessing the choice of venue may be significantly driven by things we don't know till we start getting talks scheduled and a feel for interest?

**Comment by jfryman** [comment]
@cwage: It's a guesstimate based on several discussions with previous organizers. A super conservative estimate is ~75 attending for the first bit. So, 150 is our base minimum. On the top end, 350 is not out of the ordinary.

I think we need to set a cap. I'm not opposed to selecting a venue that seats <150, since we are still exploring. I have received a lot of interest however, and from outside the BNA area, so I don't think 150 is unreasonable to target.

**Comment by jfryman** [comment]
@cwage do you have any thoughts or leads here? I'll start brainstorming, but I'm curious if you were just poking at the question or if you had something in mind.

**Comment by jfryman** [comment]
@jcockhren is following up with a contact at Music City Center. In addition, Nick Wallace @ EMC said he shared a PDF of venue locations. I'm going to dig that up and put some info up here.

**Comment by jfryman** [comment]
@jcockhren Any updates on MCC?

**Comment by jcockhren** [comment]
@jfryman VMWare User Group has the MCC booked on Nov. 10th. Sooo. Meh.

We can pursue the same event space used by HackTN. 
I spoke with Randi Events and they have 2 event spaces that would fit our needs and occupancy requirements. Both of them are currently available for our tentative dates. For either, to reserve they require $2500 + signed contract. For each space, below is the pricing for each day and total.

- [Avenue](http://www.nashvilleeventspace.com/venues/avenue/) -> Thurs 10th: $2185, Fri 11th: $3535 = **Total: $5720**
- [Track One](http://www.nashvilleeventspace.com/venues/track-one/) -> Thus 10th: $2850, Fri 11th: $3350 = **Total: $6200** (Same space used by HackTN)

**Comment by jfryman** [comment]
You know which is closer to downtown? Ideally, folks do not have to travel far from hotel to event to downtown, or at least we provide transit options.
What do we get for the $$? Help with setup and whatnot, or just raw access to the space?
Oh, and VictorOps is about to give us $$ :)

-James
On Mon, Apr 11, 2016 at 8:17 PM, Jurnell Cockhren <notifications@github.com> wrote:
@jfryman [https://github.com/jfryman] VMWare User Group has the MCC booked on Nov. 10th. Sooo. Meh.

We can pursue the same event space used by HackTN.
I spoke with Randi Events and they have 2 event spaces that would fit our needs and occupancy requirements. Both of them are currently available for our tentative dates. For either, to reserve they require $2500 + signed contract. For each space, below is the pricing for each day and total.

 * Avenue [http://www.nashvilleeventspace.com/venues/avenue/] -> Thurs 10th: $2185, Fri 11th: $3535 = Total: $5720
 * Track One [http://www.nashvilleeventspace.com/venues/track-one/] -> Thus 10th: $2850, Fri 11th: $3350 = Total: $6200 (Same space used by HackTN)

**Comment by jfryman** [comment]
We have officially signed a contract with aVenue. Working on official payment, but we've got it!
