### ISSUE TITLE
Twitter link on website is incorrect

### ISSUE THREAD

**Issue by stephenyeargin** [DevOpsDaysBNA/discussions#11]
Not sure if the event will be tagged `DevOpsDaysBNA` or `DevOpsDaysNash`, but the link on the [website](http://www.devopsdays.org/events/2016-nashville/welcome/) is broken.

Exists: https://twitter.com/devopsdaysnash
Does Not Exist: https://twitter.com/devopsdaysbna

/cc @jfryman

**Comment by jfryman** [comment]
This has since been resolved. https://twitter.com/devopsdaysbna is the account to match up with the branding we've been doing.
