### ISSUE TITLE
Sponsors for DevOpsDays 2016

### ISSUE THREAD

**Issue by jfryman** [DevOpsDaysBNA/discussions#2]
I would like to start collaborating on companies in the Mid-West (Nashville, Memphis, Knoxville, Chattanooga, Georgia) that might be willing to contribute. Throw in places we can explore.

**Comment by jcockhren** [comment]
Here's a start short list of companies that we should approach. Add more. :

- [ ] IBM
- [ ] SaltStack
- [ ] Juice Analytics (Nashville)
- [ ] Fastly

**Comment by jfryman** [comment]
Some more to approach:

* [ ] StackStorm (why not...)
* [ ] Heroku
* [ ] GitHub
* [ ] VictorOps
* [ ] Netways
* [ ] PuppetLabs
* [ ] Chef
* [ ] Salt

**Comment by jfryman** [comment]
Let's not forget local friends! :musical_note: :city_sunrise: ...

* [ ] EMC
* [ ] Emma
* [ ] Raven
* [ ] Lonely Planet

**Comment by jcockhren** [comment]
More:
- [ ] IBM
- [ ] Eventbrite

**Comment by jfryman** [comment]
I spoke with @maxbeizer on Friday this week. This is a follow-up from that conversation to get him involved so we can figure out who to talk to, and what sort of email to write to beg for $$. :dancer:

**Comment by maxbeizer** [comment]
I will reach out to the appropriate Heroku people. Had you all considered Metova? I know a few people over there.

**Comment by jfryman** [comment]
@maxbeizer that's a good idea. thanks.

**Comment by leejones** [comment]
I'd be happy to ask at Lonely Planet. Do we have some standard info and levels for potential sponsors?

**Comment by jfryman** [comment]
@leejones that's most kind of you! :bow:. Here is our current pricing list:

Gold - 5k (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=C5HCDXB9A4R54)
Silver - 2.5k (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5JX3UX9F5TN4G)
Bronze - 1k (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FC9Z3ACVBGZJJ)

Some extra details can be found here: https://dl.dropboxusercontent.com/u/443584/DevOpsDays/DevOpsDays%20BNA%20-%20Sponsorship%20Packages.pdf

I am more than happy to meet with folks on your end, @leejones, so lmk.

**Comment by jfryman** [comment]
I reached out to @rjfryman today to scope out getting in front of someone at Metova for sponsorships. We'll see how that goes.

**Comment by jfryman** [comment]
@leejones any feedback from your team?

I have submitted requests to:

* VictorOps
* GitHub
* PuppetLabs

Going to follow-up with the local leaders here and see who else is interested from the Nashville DevOps Leadership committee.

**Comment by leejones** [comment]
@jfryman thanks for the reminder. The person I need to speak with is out till next week. Let me get back to you.

**Comment by jfryman** [comment]
Woot! I am pleased to announce our initial sponsors.

* Raven Tools has pledged Silver level support.
* VictorOps has pledged Gold level support.

Many thanks to our first sponsors, and hope we have many more come!

**Comment by jfryman** [comment]
I just sent out the following email to the Nashville DevOps Leadership group. I hope that we'll see some initial interest from the companies represented in this group, including:

* Shadow-soft
* Advizex
* EMC
* VMWare
* HealthStream

```
From: James Fryman <james@fryman.io>
Subject: DevOpsDays Nashville Sponsorships
Date: April 12, 2016 at 6:12:39 PM GMT-3

Hello Nashville DevOps Leadership Team!

The team here continues to press on getting DevOpsDays organized for Nashville! I’d like to share with you all the current status, as well as share information re: sponsorship and how you can get involved.

Today, the organization team is comprised of the following individuals:
* Eliza Marcum
* James Fryman
* Jurnell Cockhren
* Chris Wage
* Nick Wallace

We’re doing something new here. In the spirit of openness and collaboration (some core tenants of DevOps), we are actually doing *all* planning publicly on GitHub. If you would like to take a look at this, please check it out at https://github.com/DevOpsDaysBNA/discussions/issues.

We’re still very early in planning, so we’re trying to narrow down our actual location. However, that is in motion, and we hope to have a place scheduled by the end of the month (we currently have available funds for deposit from local sponsors, and are narrowing down properties). We are also getting our website updated with our current sponsor list. This should also be done this week.

Our current sponsorship offering is boilerplate for the DevOpsDays conference series, and has three standard levels: Gold/Silver/Bronze. You can find that download at https://dl.dropboxusercontent.com/u/443584/DevOpsDays/DevOpsDays%20BNA%20-%20Sponsorship%20Packages.pdf. Inside, this contains all the various details about the sponsorship packages. Everything that is currently mentioned in this document will be honored once we update our document to include exact information about what each package will provide you or your team for sponsoring. Today, it looks like this:

* Gold (5000 USD): 6 included tickets + a 'promo' spot during talk intermissions + the ability to have a simple table/sponsor presence at the venue.

* Silver (2500 USD): 4 included tickets, sometimes half a table depending on the local event's choices, sometimes just a single shared swag table.

* Bronze (1000 USD): 2 included tickets, sometimes can leave stickers/flyers/etc in public spaces 

* Media Sponsor: get logo on the site and acknowledgement on social media. Used for media outlets and other conferences that are interested in cross-promotion with you 

If any of you would like to connect via Hangout or Telephone to further discuss the sponsorship opportunities, I would be most happy to take some time and chat with you and/or any other members of your team needed. Please let me know and I would be more than happy to setup a time to chat. If you’re feeling especially generous, we already have our payment processor setup, being managed by ConferenceOps, and they are handling all $$ logistics. We are happy to go through standard company finance processes if need be (Purchase Orders, Invoices, etc), and the ConferenceOps team is equipped to help manage that process once your company agrees to sponsorship.

Gold ($5k): https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=C5HCDXB9A4R54
Silver: ($2.5k) https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5JX3UX9F5TN4G
Bronze: ($1k) https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FC9Z3ACVBGZJJ
Media: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NPBGTQ7FSVZKA 

In addition, we are still looking for sponsors for our evening activity, planned the first evening (Nov 10). We are currently negotiating a price with Pinewood Social as this is a good friendly community place, and should easily accommodate the number of attendees we are planning. 

If you have any other questions, please do not hesitate to let me know. 

Thank you very much for your consideration.

Respectfully,
James Fryman
```

**Comment by jfryman** [comment]
Hey friends!

The sponsorship page has been updated! Has lots more details, as well as links to Click Now and donate. An updated prospectus also is ready to go.

Take a look, ask questions if you have them

http://www.devopsdays.org/events/2016-nashville/sponsor/

**Comment by jfryman** [comment]
Pleased to announce GitHub as a Gold sponsor! We just received notification from Aki Naito, Head of Field and Channel Marketing, that they will also be sponsoring us this year.

:rocket: :moon: :octocat:

**Comment by jfryman** [comment]
We're tracking this in our spreadsheet.

https://docs.google.com/spreadsheets/d/1S69C6m9-VqdKRcmm7kpIMbHx0Xfq6KhZRCWHjzRPniI/edit#gid=963800529

**Comment by maxbeizer** [comment]
I mentioned it in IRC, but I'm sorry to say that Heroku is out. The lady who originally said yes, took another job. They did send me a swag box, though. So if you want some Heroku stuff, LMK.
