### ISSUE TITLE
Insurance

### ISSUE THREAD

**Issue by jfryman** [DevOpsDaysBNA/discussions#25]
Need to find and figure out insurance for:

* [x] event space (Nov 10/11)
* [ ] Evening event (Nov 10).

On the website, it is recommended to see if we can get TULIP Event Insurance https://www.onebeaconentertainment.com/OneBeaconEntertainment/pages/products/tulip.page. I could not find anything for our event space that would qualify for eligibility.

I put in a general inquiry to https://www.kandkinsurance.com, Nationwide's referral for Event Insurance to cover both scenarios.

/cc @cwage

**Comment by jfryman** [comment]
Insurance for the evening space has been purchased. Once we have confirmation of where we're going to do the evening space, then I'll execute a buy for that space as well.

**Comment by cwage** [comment]
:+1: Awesome -- that will be a relief. Did you get the TULIP thing linked above? Is there a link to their coverage/policies? Might be good to note any specific things we should make sure *not* to do to avoid liability outside the policy.

**Comment by jfryman** [comment]
@cwage No, I ended up getting something else. Everyone I spoke with just said get "General Liability", so I got a policy. Links here, which should contain all the info. We need to ask to also see if aVenue needs to be on the policy as well.

* https://drive.google.com/open?id=0BxIbEOIdhpThUWVIRWlXSmdPcGc
* https://drive.google.com/open?id=0BxIbEOIdhpThbVlwOWo3eWhBT00

**Comment by jfryman** [comment]
OK. We have insurance for both venues.
