### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by aelder** [DevOpsDaysBNA/discussions#27]
**Nov. 8 status**

One camera is confirmed compatible - the other may turn out to be incompatible. If that's the case we would be limited to a single camera shoot unless cwage's camera works or we find another replacement.

I'll know for sure this afternoon after I test the Blackmagic switcher setup.

**Nov. 8 Audio Status**

We need to buy or rent the Behringer today asap - or we need to choose to use analog into the camera for the audio source. If tobinquadros has a rental source that would make it easier. This is a $350 cost unless a rental is available in time. 

**Nov. 8 Budget**

> HDMI Cables - Adapters	$30.35
> HDMI Cables Thunderbolt Cable	$37.67
> Gaffers Tape	$20.84
> Blackmagic Ultrastudio	$153.72
> Panasonic Power Adapter	$153.49
> Blackmagic ATEM Production Studio 4K Switcher Rental - theft and damage waiver included	$180.26 	
> 	
> Total $576.33 as of now.

**Rent from LensRentals - local pickup in Brentwood**

- [ ] Manfrotto 502 Fluid Head w/ 475B Pro Tripod (unless someone has a tripod to donate for the duration) @cwage is looking for his tripod so this is hopefully solved.
- [x] Black Magic ATEM Television Studio
- [x] HDMI cables for whatever run we have from cameras to switcher (not available to rent in time, purchased)

**Audio**

Assuming analog audio from the venue mixer, we need a way to convert it to digital for the switcher. This seems to be most commonly done with a Behringer DEQ2496. This isn't available to rent, but is a $300 buy. Will also need a BNC M/ RCA cable. The alternative is to run audio from the mixer into the GH4 camera, which has a stereo 3.5mm input. The GH4 will then bundle the audio to the mixer over HDMI. This should be fine, but is more susceptible to oddities. It also means that camera needs to be located close to the mixer or audio source. Other suggestions would also be helpful here.

**Things we need people to bring**

- [ ] Grounded extension cords
- [ ] Power Strips
- [ ] Grounded Splitters

**Production**

I'll put together some transition and stand by graphics for the stream. Access to a vector version of the event logo and any sponsors or other logos that need to be displayed would be good.

**Status:**
**Purchased**

- Panasonic constant power supply
- Sony constant power supply
- Micro HDMI to HDMI x2
- 25 foot HDMI cable x2
- Black Magic HDMI to Thunderbolt interface
- Gaffers tape
- HDMI coupler x3
- Thunderbolt cable .5 meter

**Reserved rental**
- Black Magic 4k switch

**Comment by aelder** [comment]
[https://i.imgur.com/SaSUST4.png](url)

**Comment by jfryman** [comment]
Here are media assets: https://www.dropbox.com/sh/pgo08o4anasjze1/AAAbfro-DCXTHcLBCKauf5VHa?dl=0

**Comment by tobinquadros** [comment]
Cool

- You may want a small external monitor for viewing the video feeds separate from the Control Laptop display.
- Are we syncing anything with timecode? 😄 
- Do we know what the house has available with it's audio PA setup?
  - If the house setup is limited than this seems good, we can run balanced outs from the house mixer to something like a Behringer DEQ2496, and AES/EBU into the switcher.
  - If they have a decent house mixer than we may be better suited to record "direct outs" from multiple channels instead of the live 2-mix. This would be better for post-production if that is a concern. We would need a multichannel Analog-to-Digital converter instead of the Behringer DEQ2496. I'm sure I can find one for rental.

**Comment by tobinquadros** [comment]
Actually, after another look I see the ATEM Television Studio only supports 1 AES/EBU unbalanced audio input 🤔 . Sounds like the Behringer (or any 2-channel A/D converter with AES outs) will be fine as long as we have an adapter from Balanced AES to BNC. Either way that seems like a much better situation than the analog camera inputs.

**Comment by aelder** [comment]
- I've got a monitor I can bring, need to double check on the input.
- We have a laissez faire attitude towards timecode.
- This is one of the main issues - have no idea what the house setup is like or what we can plug into. Access is available Wed. and hopefully there aren't any surprises.

If you don't mind, I'd like to transfer as much of the audio side to you as possible, it's the area I know the least about in this setting.

**Comment by tobinquadros** [comment]
Sure I'd be happy to assist with the audio stuff, but as you mentioned there are some weary unknowns about the house setup at this point.

Other notes:
- No timecode shouldn't be a problem as long as we ensure all devices are set to record at the same resolution (24bit/48kHz).
- Do they have a house engineer to ring out the mics/monitors and manage input levels and mutes?
- Extra cables, extensions cords, etc. should just be rented as a safety plan.
- What are the camera models being used? (To check audio settings compatibility)
- What is the Hardware Encoder in the diagram? Is it for h.264 to some streamable format?
- Are you doing some basic post-production and editing of talks?
- How much capacity is on the external storage? Do we have a RAID or redundant drives? (Failure is not an option 😄 )

**Comment by aelder** [comment]
- Do they have a house engineer to ring out the mics/monitors and manage input levels and mutes?

> @jfryman question probably - we can find this out Wed. when we have venue access.

- Extra cables, extensions cords, etc. should just be rented as a safety plan.

> yeah definitely

- What are the camera models being used? (To check audio settings compatibility)

> Panasonic GH4 is good to go, other cameras are a Sony A7r and NEX 6 - both are untested at this point.

- What is the Hardware Encoder in the diagram? Is it for h.264 to some streamable format?

> Blackmagic Ultrastudio - HDMI to Thunderbolt interface for the streaming laptop. Encoder ended up being the wrong word.

- Are you doing some basic post-production and editing of talks?

> Not sure, but they at least need to be recorded so that can be done.

- How much capacity is on the external storage? Do we have a RAID or redundant drives? (Failure is not an option 😄 )

> I don't know at this point. It's really not redundant enough, and very 'make what we have work.' The GH4 can record to SD card - but it won't have the audio mix.

**Comment by aelder** [comment]
I ordered the Behringer and the bnc rca cable. They will be here today and I should have all the pieces to actually test the setup fully.

Is there a local rental house that you know of for things like extension cords?

**Comment by tobinquadros** [comment]
Sounds like good progress.

> Is there a local rental house that you know of for things like extension cords?

- Blackbird audio rentals, or Trew audio has cabling for rent.

- We could possibly get by with just a standby hard drive in case of failure, and use it for master/safety backups. But overall the 4k video and 24/48 audio will require large disk capacity over two days.
  - GH4 4k video * 1hr = 42GB
  - Stereo 24-bit/48kHz audio * 1hr = 1GB
  - Minimum required disk available (with only one camera): 43GB * 8hr * 2days = 688GB
    - We could probably get by no problem with two 2TB HD's. This will allow room for post-production editing and master/safety back-ups.

**Comment by aelder** [comment]
I'm not set on a resolution, but I imagine 1080p is probably good enough. That would drop us down to 50mbps or so and make it a lot less stressful on storage bandwidth.

**Comment by tobinquadros** [comment]
Ya, 4k is overkill. But we do want two drives.

**Comment by jfryman** [comment]
I have a LaCie Thunderbolt External Enclosure w/ 2 3TB drives. Will need to format and setup a software RAID, but totally doable.

**Comment by tobinquadros** [comment]
That would be awesome. Can we format and RAID from OSX Disk Utility? Or is there driver software we can use?
