### ISSUE TITLE
Opening up the Call-for-Papers

### ISSUE THREAD

**Issue by jfryman** [DevOpsDaysBNA/discussions#7]
At some point, we will need to start advertising the CFP. Our blockers here are:

* [x] Secure a venue ( #1 )
* [ ] Update the main website with additional information (http://www.devopsdays.org/events/2016-nashville/

We also need to lock it down so we can advertise and generate buzz. Here's what I'm thinking right now re: CFP.

* I have reached out to a few colleagues already, and they are considering. If you have someone in mind you think would be great to have here and speak, drop them in this list and let's reach out to them and see if they are available.

Proposed dates for CFP: June 01 - Aug 31, 2016. Too long, too short?

We'll get another issue open when we start receiving talks to discuss how we'll review and make selections.

**Comment by jcockhren** [comment]
Now with the first requirement satisfied (venue). 

How about we extend the window from June 1st to Sept 15th?

**Comment by jfryman** [comment]
Yeah, That works for me.

**Comment by leejones** [comment]
How much time does that leave to review submissions and notify people?

**Comment by jfryman** [comment]
@leejones only about 6-7 weeks if we push to Sept 15. That might be a fast. There is also nothing saying we can't open the CFP a bit earlier (say, in two weeks) to start allowing submissions to filter in.

**Comment by jfryman** [comment]
On this note... it seems the CFP window is typically only 8 weeks. June 1 - Aug 31 should still be OK.

@DevOpsDaysBNA/core-organizers: If you have folks that you'd like to put on the short list, or to reach out to... now is the time. Please reach out, and post notes.
